# Generated by Django 4.0.3 on 2022-05-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='SorlPhoto/%Y', verbose_name='IMAGE'),
        ),
    ]
